### ISSUE TITLE
Clone repo error!!!

### ISSUE THREAD

**Issue by ITHealer** [nyadla-sys/whisper.tflite#14]
![image](https://github.com/nyadla-sys/whisper.tflite/assets/94621494/dfb96c49-be1e-4862-845d-2520b7876e70)

I think the cause is the LICENSE.txt:Zone.Identifier file
Is there any way to solve this problem?

**Comment by vilassn** [comment]
Updated code. Removed glf dependency. Please checkout latest code freshly.
