### ISSUE TITLE
How to add TfLite GPU delegate 

### ISSUE THREAD

**Issue by suyash-narain** [nyadla-sys/whisper.tflite#28]
Hi,

how do we add TfLite GPU delegate to whisper.tflite c++ app?

whenever i try to add gpu delegate options to the file TFLiteEngine.cpp 
```
auto* delegate = TfLiteGpuDelegateV2Create(nullptr);
if (g_whsiper_tflite.interpreter->ModifyGraphWithDelegate(delegate) != kTfLiteOk) return "";
```
before the line  
https://github.com/nyadla-sys/whisper.tflite/blob/29fe1adf2bd954b01f573c5d6dfed2dc009cb363/whisper_android/app/src/main/cpp/TFLiteEngine.cpp#L195

I get the error 

> ld: error: undefined symbol: TfLiteGpuDelegateV2Create

or I get the error

> no matching function to call TfLiteGpuDelegateV2Create

Am following https://www.tensorflow.org/lite/android/delegates/gpu_native#enable_gpu_acceleration steps to enable GPU delegate. Not sure how to add the delegate here.

thanks

**Comment by nyadla-sys** [comment]
tflite gpu_delegate is not working as some of the ops from whisper.tflite are not supported in gpu ops

**Comment by suyash-narain** [comment]
so shouldn't these ops simply fallback onto CPU by default?

**Comment by suyash-narain** [comment]
makes sense. thanks
