### ISSUE TITLE
Could you share how to get one DTLN Tflite model?

### ISSUE THREAD

**Issue by saraphinesER** [nyadla-sys/whisper.tflite#39]
Hello, @nyadla-sys ,
I noticed the DTLN tflite model you have is one full integer quantization TFLite model (whisper.tflite/models/dtln_quantized.tflite), while as I knew the [breizhn/DTLN](https://github.com/breizhn/DTLN) separate into 2 TFLite models. (convert_weights_to_tf_lite.py)
I am wondering how to get them into one as yours.
Could you please share the script you used to get your dtln_quantized.tflite?
That will be very helpful to me. I would really appreciate your help if you could share.
Thanks.

**Comment by saraphinesER** [comment]
Thanks for nyadla-sys kindness to correct my misunderstanding of the quantized DTLN Tflite model.
It's only a TFLite conversion from stage1, which is 'model_1', not a conversion from combination of 2 models.

**Comment by nyadla-sys** [comment]
> Thanks for nyadla-sys kindness to correct my misunderstanding of the quantized DTLN Tflite model. It's only a TFLite conversion from stage1, which is 'model_1', not a conversion from combination of 2 models.

Correct

**Comment by nyadla-sys** [comment]
if you could integrate dtln with whisper tflite model,please share the working pipeline thanks
